export declare const vars: {
    breakpoints: Record<import("./types").SizeVariant, string>;
    spaces: {
        readonly none: "0px";
        readonly auto: "auto";
        readonly px: "0.0625rem";
        readonly '3xs': "0.375rem";
        readonly '2xs': "0.75rem";
        readonly xs: "0.875rem";
        readonly sm: "1rem";
        readonly md: "1.5rem";
        readonly lg: "2.25rem";
        readonly xl: "2.5rem";
        readonly '2xl': "3rem";
        readonly '3xl': "5.625rem";
        readonly '4xl': "9.375rem";
    };
    maxWidths: {
        readonly none: "none";
        readonly xs: "550px";
        readonly sm: "738px";
        readonly md: "960px";
        readonly lg: "1200px";
        readonly xl: "1440px";
        readonly '2xl': "1760px";
        readonly full: "100%";
    };
    colors: {
        primaryOneDefault: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        primaryOneLight: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        primaryOneDark: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        secondaryDefault: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        secondaryLight: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        secondaryDark: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        textDefault: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        textLight: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        textDark: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        dangerDefault: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        dangerLight: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        dangerDark: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        successDefault: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        successLight: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        successDark: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        warningDefault: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        warningLight: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        warningDark: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        white: "#ffffff";
        black: "#000000";
        transparent: "transparent";
        inherit: "inherit";
        mark060: string;
        mark070: string;
        mark080: string;
        mark090: string;
        mark110: string;
        mark100: string;
        mark120: string;
        mark130: string;
        mark140: string;
        skeletonLight060: string;
        skeletonLight070: string;
        skeletonLight080: string;
        skeletonLight090: string;
        skeletonLight110: string;
        skeletonLight100: string;
        skeletonLight120: string;
        skeletonLight130: string;
        skeletonLight140: string;
        oldIvory060: string;
        oldIvory070: string;
        oldIvory080: string;
        oldIvory090: string;
        oldIvory110: string;
        oldIvory100: string;
        oldIvory120: string;
        oldIvory130: string;
        oldIvory140: string;
        graphite060: string;
        graphite070: string;
        graphite080: string;
        graphite090: string;
        graphite110: string;
        graphite100: string;
        graphite120: string;
        graphite130: string;
        graphite140: string;
        whiteSmoke060: string;
        whiteSmoke070: string;
        whiteSmoke080: string;
        whiteSmoke090: string;
        whiteSmoke110: string;
        whiteSmoke100: string;
        whiteSmoke120: string;
        whiteSmoke130: string;
        whiteSmoke140: string;
    };
    shadows: {
        readonly none: "none";
        readonly xs: "0px 0px 0.2px rgba(0, 0, 0, 0.031), 0px 0px 0.5px rgba(0, 0, 0, 0.044), 0px 0px 0.9px rgba(0, 0, 0, 0.056), 0px 0px 1.6px rgba(0, 0, 0, 0.069), 0px 0px 5px rgba(0, 0, 0, 0.2)";
        readonly sm: "0px 0px 0.5px rgba(0, 0, 0, 0.031),0px 0px 1.1px rgba(0, 0, 0, 0.044), 0px 0px 2px rgba(0, 0, 0, 0.056), 0px 0px 3.5px rgba(0, 0, 0, 0.069), 0px 0px 11px rgba(0, 0, 0, 0.2)";
        readonly md: "0px 0px 0.7px rgba(0, 0, 0, 0.031), 0px 0px 1.5px rgba(0, 0, 0, 0.044), 0px 0px 2.7px rgba(0, 0, 0, 0.056), 0px 0px 4.8px rgba(0, 0, 0, 0.069), 0px 0px 15px rgba(0, 0, 0, 0.2)";
        readonly lg: "0px 0px 1.6px rgba(0, 0, 0, 0.031), 0px 0px 3.6px rgba(0, 0, 0, 0.044), 0px 0px 6.2px rgba(0, 0, 0, 0.056), 0px 0px 11.3px rgba(0, 0, 0, 0.069), 0px 0px 35px rgba(0, 0, 0, 0.2)";
        readonly xl: "0px 1px 2.1px rgba(0, 0, 0, 0.028), 0px 2.3px 5px rgba(0, 0, 0, 0.04), 0px 4.4px 9.4px rgba(0, 0, 0, 0.05), 0px 7.8px 16.8px rgba(0, 0, 0, 0.06), 0px 14.6px 31.3px rgba(0, 0, 0, 0.072), 0px 35px 75px rgba(0, 0, 0, 0.2)";
        readonly '2xl': "0px 1.9px 3.3px rgba(0, 0, 0, 0.037), 0px 4.7px 8px rgba(0, 0, 0, 0.053), 0px 8.8px 15px rgba(0, 0, 0, 0.065), 0px 15.6px 26.8px rgba(0, 0, 0, 0.077), 0px 29.2px 50.1px rgba(0, 0, 0, 0.093), 0px 70px 120px rgba(0, 0, 0, 0.2)";
    };
    typography: {
        fontWeights: {
            readonly normal: "400";
            readonly bold: "700";
        };
        fontSizes: {
            default: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
            xs: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
            sm: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
            md: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
            lg: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
            xl: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
            '2xl': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
            '3xl': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
            '4xl': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
            '5xl': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
            '6xl': `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        };
        fonts: {
            readonly primaryFontFamily: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
            readonly secondaryFontFamily: `var(--${string})` | `var(--${string}, ${string})` | `var(--${string}, ${number})`;
        };
    };
};
